- name: GTK | Create /.config/gtk-3.0 directory
  file:
    path: ~/.config/gtk-3.0
    state: directory

- name: GTK | Symlink gtk-3.0 config
  file:
    src: "{{ ansible_env.PWD }}/roles/gtk-3.0/files/{{ item }}"
    path: "~/.config/gtk-3.0/{{ item }}"
    state: link
    follow: yes
    force: yes
  loop:
    - settings.ini
    - bookmarks
