- name: FIREFOX | Install Firefox  on Linux
  become: yes
  package:
    name:
      - firefox
    state: latest
  when: ansible_facts['os_family'] != "Darwin"

- name: FIREFOX | Install Firefox on Macos (Cask)
  community.general.homebrew_cask:
    name:
      - firefox
    state: latest
    greedy: true
    accept_external_apps: true
  when: ansible_facts['os_family'] == "Darwin"

- name: FIREFOX | Create chrome directory
  file:
    path: $HOME/.mozilla/firefox/49z9or9s.default-release/chrome
    state: directory

- name: FIREFOX | Symlink userChrome.css
  file:
    src: '{{ ansible_env.PWD }}/roles/firefox/files/{{ item }}'
    path: '$HOME/.mozilla/firefox/49z9or9s.default-release/chrome/{{ item }}'
    state: link
    follow: yes
    force: yes
  loop:
    - userChrome.css
