- name: PARU | Install prerequsite
  pacman:
    name:
      - git
      - base-devel
    state: latest
  when: ansible_facts['os_family'] == "ArchLinux"

- name: PARU | git clone paru
  git:
    repo: https://aur.archlinux.org/paru.git
    dest: /tmp
    single_branch: yes
    version: master
  when: ansible_facts['os_family'] == "ArchLinux"

- name: PARU | Running makepkg
  command: cd /tmp/paru && makepkg -si
  when: ansible_facts['os_family'] == "ArchLinux"

- name: PARU | Create /.config/paru directory
  file:
    path: '~/.config/paru'
    state: directory


- name: PARU | Symlink paru config
  file:
    src: '{{ ansible_env.PWD }}/roles/package_manager/files/{{ item }}'
    path: "~/.config/paru/{{ item }}"
    state: link
    follow: yes
    force: yes
  loop:
    - paru.conf
