- name: install bash libs on linux
  package:
    name:
      - pfetch
      - lolcat
      - neofetch
    state: present
  become: yes

- name: symlink bashrc on Linux
  file:
    src: "{{ ansible_env.PWD }}/roles/bash/files/{{ item }}"
    path: "~/{{ item }}"
    state: link
    follow: yes
    force: yes
  loop:
    - .bashrc
    - .dircolors
