- name: HYPRLAND | Install hyprland on Linux
  pacman:
    name:
      - hyprland-git
      - dunst
      - wf-recorder
      - wlogout
      - xdg-desktop-portal-hyprland
    state: latest
    executable: paru
    extra_args: --builddir /var/cache/paru

- name: HYPRLAND | Create /.config/hypr directory
  file:
    path: ~/.config/hypr
    state: directory

- name: HYPRLAND | Symlink hypr config
  file:
    src: "{{ ansible_env.PWD }}/roles/hypr/files/{{ item }}"
    path: "~/.config/hypr/{{ item }}"
    state: link
    follow: yes
    force: yes
  loop:
    - hyprland.conf
    - keybinds.conf
    - startup.conf

- name: HYPRLAND | Symlink startw script
  become: yes
  file:
    src: "{{ ansible_env.PWD }}/roles/i3/files/{{ item }}"
    path: "/usr/bin/{{ item }}"
    state: link
    follow: yes
    force: yes
  loop:
    - startw