- name: install mpv on linux
  package:
    name:
      - mpv
    state: latest
  become: yes

- name: create mpv config directory
  file:
    path: ~/.config/mpv
    state: directory

- name: symlink mpv conf on Linux
  file:
    src: "{{ ansible_env.PWD }}/roles/mpv/files/{{ item }}"
    path: "~/.config/mpv/{{ item }}"
    state: link
    follow: yes
    force: yes
  loop:
    - mpv.conf
