- name: Install mpv on Linux
  package:
    name:
      - mpv
    state: latest
  become: yes

- name: Create /.config/mpv directory
  file:
    path: ~/.config/mpv
    state: directory

- name: Symlink mpv config
  file:
    src: "{{ ansible_env.PWD }}/roles/mpv/files/{{ item }}"
    path: "~/.config/mpv/{{ item }}"
    state: link
    follow: yes
    force: yes
  loop:
    - mpv.conf