- name: Setup DeathStar environment
  hosts: localhost
  vars:
    cert_path: /etc/ssl/certs/ca-certificates.crt
  roles:
    - package_manager
    - common
    - cpu
    - gpu
    - git
    - zsh
    - i3
    - i3blocks
    - dunst
    - flameshot
    - mpv
    - gtk-3.0
    - rofi
    - picom
    - tmux
    - vim
    - helix
    - xscreensaver
    - wezterm
    - pipewire
  tasks:
    - import_tasks: roles/packages/cli.yml
    - import_tasks: roles/packages/ctf.yml
    - import_tasks: roles/packages/docker.yml
    - import_tasks: roles/packages/fonts.yml
    - import_tasks: roles/packages/gui.yml
    - import_tasks: roles/packages/k8s.yml
    - import_tasks: roles/packages/networkmanager.yml
    - import_tasks: roles/packages/nfc.yml
    - import_tasks: roles/packages/python.yml
    - import_tasks: roles/packages/tools.yml
