- name: Setup SpaceCruiser environment
  hosts: localhost
  vars:
    cert_path: /opt/homebrew/etc/openssl@1.1/cert.pem
  roles:
    - zsh
    - alacritty
    - bash
    - cpu
    - git
    - tmux
    - vim
    - helix