- name: Setup SpaceCruiser environment
  hosts: localhost
  vars:
    cert_path: /opt/homebrew/etc/openssl@1.1/cert.pem
  roles:
    - common
    - zsh
    - firefox
    - discord
    - vim
    - git
    - mpv
    - tmux
    - obsidian
    - games
  tasks:
    - import_tasks: roles/packages/hashicorp.yml
    - import_tasks: roles/packages/cli.yml
    - import_tasks: roles/packages/ctf.yml
    - import_tasks: roles/packages/gui.yml
    - import_tasks: roles/packages/docker.yml
    - import_tasks: roles/packages/macos.yml
    - import_tasks: roles/packages/k8s.yml
    - import_tasks: roles/packages/nfc.yml
    - import_tasks: roles/packages/tools.yml
