- name: PACKAGE | Install AMD driver on Linux
  aur:
    use: yay
    name:
      - xf86-video-amdgpu
      - lib32-mesa
      - vulkan-radeon
      - lib32-vulkan-radeon
      - vulkan-icd-loader
      - lib32-vulkan-icd-loader
      - linux-zen
    state: latest
