- name: PACKAGES | Install CLI tools on Linux
  pacman:
    name:
    name:
      - zip
      - unzip
      - unrar
      - p7zip
      - screen
      - jq
      - wget
      - git
      - ncdu
      - termdown
      - htop
      - xclip
      - minicom
      - ffmpeg
      - keybase
      #- mkdocs
      #- mkdocs-material-pymdownx-extras
      #- mkdocs-material
      - openvpn
      - pywal-git
    state: latest
    executable: paru
    extra_args: --builddir /var/cache/paru
  when: ansible_facts['os_family'] == "ArchLinux"