- name: PACKAGES | Install CTF tools on Linux
  pacman:
    name:
      - ghidra
      - sonic-visualiser
      - volatility
      - hexedit
      - strace
      - ltrace
      - burpsuite
      - gnu-netcat
      - gobuster
      - hydra
      - john
      - metasploit
      - msf-mpc
      - nmap
      - seclists
      - sqlmap
      - wpscan
      # - msitools
    state: latest
    executable: paru
    extra_args: --builddir /var/cache/paru
  when: ansible_facts['os_family'] == "ArchLinux"

- name: PACKAGES | Install CTF tools on Macos
  community.general.homebrew:
    name:
      - volatility
      - hexedit
      - netcat
      - gobuster
      - hydra
      - john
      - nmap
    state: latest
  when: ansible_facts['os_family'] == "Darwin"

- name: PACKAGES | Install CTF tools on Macos (Cask)
  community.general.homebrew_cask:
    name:
      - ghidra
      - sonic-visualiser
      - burp-suite
      - metasploit
    state: latest
    greedy: true
    accept_external_apps: true
  when: ansible_facts['os_family'] == "Darwin"
