- name: PACKAGES | Install CTF tools on Linux
  pacman:
    name:
      - ghidra
      - sonic-visualiser
      - volatility
      - hexedit
      - strace
      - ltrace
      - burpsuite
      - gnu-netcat
      - gobuster
      - hexedit
      - hydra
      - john
      - metasploit
      - msf-mpc
      - nmap
      - seclists
      - sqlmap
      - wpscan
      # - msitools
    state: latest
    executable: paru
    extra_args: --builddir /var/cache/paru
  when: ansible_facts['os_family'] == "ArchLinux"