- name: PACKAGES | Install CTF tools on Linux
  aur:
    use: yay
    name:
      - ghidra
      - sonic-visualiser
      - volatility
      - hexedit
      - strace
      - ltrace
      # - msitools
    state: latest
