- name: PACKAGES | Install Docker & Docker compose on Linux
  pacman:
    name:
      - docker
      - docker-compose
    state: latest
    executable: yay
    extra_args: --builddir /var/cache/yay
  when: ansible_facts['os_family'] == "ArchLinux"