- name: PACKAGES | Install fonts on Linux
  pacman:
    name:
      - nerd-fonts-fira-code
      - noto-fonts-emoji
      - ttf-opensans
    state: latest
    executable: paru
    extra_args: --builddir /var/cache/paru
  when: ansible_facts['os_family'] == "ArchLinux"
