- name: PACKAGES | Install games on Linux
  aur:
    use: yay
    name:
      - lutris
      - wine-staging
      - minecraft-launcher
      - multimc5
      - steam
      - ttf-liberation
    state: latest
