- name: PACKAGES | Install GUI tools on Linux
  pacman:
    name:
      - telegram-desktop
      - signal-desktop
      - mpv
      - firefox
      - torbrowser-launcher
      - sublime-text-4
      - peek
      - arandr
      - mumble
      - teams
      - zoom
      - visual-studio-code-bin
      - plexamp-appimage
      - plex-media-player
      - slack-desktop
    state: latest
    executable: yay
    extra_args: --builddir /var/cache/yay
  when: ansible_facts['os_family'] == "ArchLinux"