- name: PACKAGES | Install GUI tools on Linux
  pacman:
    name:
      - telegram-desktop
      - signal-desktop
      - torbrowser-launcher
      - sublime-text-4
      - peek
      - arandr
      - mumble
      - teams
      - zoom
      - visual-studio-code-bin
      - plexamp-appimage
      - plex-media-player
      - slack-desktop
      - wireshark-qt
    state: latest
    executable: paru
    extra_args: --builddir /var/cache/paru
  when: ansible_facts['os_family'] == "ArchLinux"

- name: PACKAGES | Install GUI tools on Macos
  community.general.homebrew:
    name:
      - wireshark
    state: latest
  when: ansible_facts['os_family'] == "Darwin"


- name: PACKAGES | Install GUI tools on Macos (Cask)
  community.general.homebrew_cask:
    name:
      - telegram
      - signal
      - tor-browser
      - sublime-text
      - mumble
      - microsoft-teams
      - zoom
      - visual-studio-code
      - plexamp
      - plex-media-player
      - slack
    state: latest
    greedy: true
    accept_external_apps: true
  when: ansible_facts['os_family'] == "Darwin"
