- name: PACKAGES | Install Hashicorp Tools Linux
  become: yes
  package:
    name:
      - terraform
      - ansible
      - ansible-core
      - vagrant
    state: latest
  when: ansible_facts['os_family'] != "Darwin"

- name: PACKAGES | Install Hashicorp tools on Macos
  community.general.homebrew:
    name:
      - ansible
      - terraform
    state: latest
  when: ansible_facts['os_family'] == "Darwin"

- name: PACKAGES | Install Hashicorp tools on Macos (Cask)
  community.general.homebrew_cask:
    name:
      - vagrant
      - virtualbox
    state: latest
  when: ansible_facts['os_family'] == "Darwin"
