- name: Hasicorp | Install Vagrant
  become: yes
  package:
    name:
      - vagrant
    state: latest

- name: Hasicorp | Install Ansible
  become: yes
  package:
    name:
      - ansible
      - ansible-core
      - molecule
    state: latest

- name: Hasicorp | Install Terraform
  become: yes
  package:
    name:
      - terraform
    state: latest

- name: PACKAGES | Install Hashicorp tools on Macos
  community.general.homebrew:
    name:
      - ansible
      - terraform
    state: latest
  when: ansible_facts['os_family'] == "Darwin"

- name: PACKAGES | Install Hashicorp tools on Macos (Cask)
  community.general.homebrew_cask:
    name:
      - vagrant
    state: latest
    greedy: true
    accept_external_apps: true
  when: ansible_facts['os_family'] == "Darwin"
