- name: Hasicorp | Install Vagrant
  become: yes
  package:
    name:
      - vagrant
    state: latest

- name: Hasicorp | Install Ansible
  become: yes
  package:
    name:
      - ansible
      - ansible-core
      - molecule
    state: latest

- name: Hasicorp | Install Terraform
  become: yes
  package:
    name:
      - terraform
    state: latest