- name: PACKAGES | Install k8s tools on Linux
  pacman:
    name:
      - kubectl
      - k9s
    state: latest
    executable: paru
    extra_args: --builddir /var/cache/paru
  when: ansible_facts['os_family'] == "ArchLinux"
