- name: PACKAGES | Install Specific Mac Apps
  community.general.homebrew:
    name:
      - mas
    state: latest
  when: ansible_facts['os_family'] == "Darwin"

- name: PACKAGES | Install Specific Mac Apps (Cask)
  community.general.homebrew_cask:
    name:
      - swinsian
      - dozer
      - binary-ninja
      - tailscale
    state: latest
  when: ansible_facts['os_family'] == "Darwin"

- name: Install specific apps and also upgrade all others
  community.general.mas:
    id:
      - 441258766 # magnet
      - 937984704 # Amfetamin
      - 1451685025 # Wireguard
    state: present
    upgrade_all: true
  when: ansible_facts['os_family'] == "Darwin"

