- name: PACKAGES | Install netowrkmanager on Linux
  pacman:
    name:
      - network-manager-applet
      - networkmanager
      - networkmanager-openvpn
    state: latest
    executable: yay
    extra_args: --builddir /var/cache/yay
  when: ansible_facts['os_family'] == "ArchLinux"
