- name: PACKAGES | Install NFC tools on Linux
  pacman:
    name:
      - mfoc
      - mfcuk-git
    state: latest
    executable: yay
    extra_args: --builddir /var/cache/yay
  when: ansible_facts['os_family'] == "ArchLinux"
