- name: install nvidia gpu drivers
  aur:
    use: yay
    name:
      - nvidia
      - nvidia-utils
      - lib32-nvidia-utils
      - nvidia-settings
      - vulkan-icd-loader
      - lib32-vulkan-icd-loader
    state: present
