- name: Install NVIDIA driver on Linux
  aur:
    use: yay
    name:
      - nvidia
      - nvidia-utils
      - lib32-nvidia-utils
      - nvidia-settings
      - vulkan-icd-loader
      - lib32-vulkan-icd-loader
    state: latest
