- name: PACKAGES | Install Python on Linux
  pacman:
    name:
      - python-pip
      - python-pipenv
      - binwalk
    state: latest
    executable: paru
    extra_args: --builddir /var/cache/paru
  when: ansible_facts['os_family'] == "ArchLinux"
