- name: PACKAGES | Install Network tools on Linux
  pacman:
    name:
      - traceroute
      - wireshark-qt
      - tcpdump
      - speedtest-cli
    state: latest
    executable: paru
    extra_args: --builddir /var/cache/paru
  when: ansible_facts['os_family'] == "ArchLinux"

- name: PACKAGES | Install Network tools on Macos
  community.general.homebrew:
    name:
      - tcpdump
      - speedtest-cli
    state: latest
  when: ansible_facts['os_family'] == "Darwin"
