#- name: Install Minecraft
  #include_tasks: minecraft.yml
  #when: ansible_facts['os_family'] != "Darwin"

- name: Install Steam
  include_tasks: steam.yml

- name: Install Lutris
  include_tasks: lutris.yml
  when: ansible_facts['os_family'] != "Darwin"

- name: Install Mangohud
  include_tasks: mangohud.yml
  when: ansible_facts['os_family'] != "Darwin"
