- name: GAMES | Install steam fonts on Linux
  become: yes
  package:
    name:
      - steam
    state: latest
  when: ansible_facts['os_family'] == "ArchLinux"

- name: GAMES | Install steam fonts on Linux
  pacman:
    name:
      - ttf-liberation
    state: latest
    executable: paru
    extra_args: --builddir /var/cache/paru
  when: ansible_facts['os_family'] == "ArchLinux"

- name: GAMES | Install steam on Macos (Cask)
  community.general.homebrew_cask:
    name:
      - steam
    state: latest
    greedy: true
    accept_external_apps: true
  when: ansible_facts['os_family'] == "Darwin"
