- name: Install i3blocks on Linux
  package:
    name:
      - i3blocks
    state: latest
  become: yes

- name: Create /.config/i3blocks directory
  file:
    path: ~/.config/i3blocks
    state: directory

- name: Symlink i3blocks config
  file:
    src: "{{ ansible_env.PWD }}/roles/i3blocks/files/{{ item }}"
    path: "~/.config/i3blocks/{{ item }}"
    state: link
    follow: yes
    force: yes
  loop:
    - battery-poly
    - config