- name: install i3blocks on linux
  package:
    name:
      - i3blocks
    state: latest
  become: yes

- name: create i3blocks config directory
  file:
    path: ~/.config/i3blocks
    state: directory

- name: symlink i3blocks conf on Linux
  file:
    src: "{{ ansible_env.PWD }}/roles/i3blocks/files/{{ item }}"
    path: "~/.config/i3blocks/{{ item }}"
    state: link
    follow: yes
    force: yes
  loop:
    - battery-poly
    - config
