#!/bin/bash

CONNECTED=$(nmcli d |grep tun0 |grep connected | awk '{print $3}')

if [[ "${CONNECTED}" == "connected" ]]; then
    echo "Up"
    else
        echo "Down"
fi
#nmcli d |grep tun0 |grep connected | awk '{print $3}'

