- name: PICOM | Install picom on Linux
  pacman:
    name:
      - picom-git
    state: latest
    executable: paru
    extra_args: --builddir /var/cache/paru
  when: ansible_facts['os_family'] == "ArchLinux"

- name: PICOM | Create /.config/picom directory
  file:
    path: ~/.config/picom
    state: directory
  when: ansible_facts['os_family'] == "ArchLinux"


- name: PICOM | Symlink picom config
  file:
    src: "{{ ansible_env.PWD }}/roles/picom/files/{{ item }}"
    path: "~/.config/picom/{{ item }}"
    state: link
    follow: yes
    force: yes
  loop:
    - picom.conf
  when: ansible_facts['os_family'] == "ArchLinux"

