- name: PICOM | Install picom on Linux
  aur:
    name: picom-git
    state: present

- name: PICOM | Create /.config/picom directory
  file:
    path: ~/.config/picom
    state: directory

- name: PICOM | Symlink picom config
  file:
    src: "{{ ansible_env.PWD }}/roles/picom/files/{{ item }}"
    path: "~/.config/picom/{{ item }}"
    state: link
    follow: yes
    force: yes
  loop:
    - picom.conf
