- name: install i3 + xorg on linux
  package:
    name:
      - xorg
      - xorg-server
      - xorg-xinit
      - i3-wm
      - feh
      - gnome-keyring
    state: latest
  become: yes

- name: create i3 config directory
  file:
    path: ~/.config/i3
    state: directory

- name: symlink i3 conf on Linux
  file:
    src: "{{ ansible_env.PWD }}/roles/i3/files/{{ item }}"
    path: "~/.config/i3/{{ item }}"
    state: link
    follow: yes
    force: yes
  loop:
    - bg
    - config

- name: symlink rnd_bg
  file:
    src: "{{ ansible_env.PWD }}/roles/i3/files/{{ item }}"
    path: "/usr/bin/{{ item }}"
    state: link
    follow: yes
    force: yes
  loop:
    - rnd_bg.sh
  become: yes

- name: symlink xinitrc on Linux
  file:
    src: "{{ ansible_env.PWD }}/roles/i3/files/{{ item }}"
    path: "~/{{ item }}"
    state: link
    follow: yes
    force: yes
  loop:
    - .xinitrc
