- name: I3 | Install i3 on Linux
  package:
    name:
      - i3-wm
      - feh
      - gnome-keyring
    state: latest
  become: yes

- name: I3 | Install xorg on Linux
  package:
    name:
      - xorg
      - xorg-server
      - xorg-xinit
    state: latest
  become: yes

- name: I3 | Create /.config/i3 directory
  file:
    path: ~/.config/i3
    state: directory

- name: I3 | Symlink i3 config
  file:
    src: "{{ ansible_env.PWD }}/roles/i3/files/{{ item }}"
    path: "~/.config/i3/{{ item }}"
    state: link
    follow: yes
    force: yes
  loop:
    - config

- name: I3 | Symlink rnd_bg script
  file:
    src: "{{ ansible_env.PWD }}/roles/i3/files/{{ item }}"
    path: "/usr/bin/{{ item }}"
    state: link
    follow: yes
    force: yes
  loop:
    - rnd_bg.sh
  become: yes

- name: I3 | Symlink .xinitrc config
  file:
    src: "{{ ansible_env.PWD }}/roles/i3/files/{{ item }}"
    path: "~/{{ item }}"
    state: link
    follow: yes
    force: yes
  loop:
    - .xinitrc
