- name: FLAMESHOT | Install Flameshot on Linux
  pacman:
    name:
      - flameshot
    state: latest
    executable: paru
    extra_args: --builddir /var/cache/paru

- name: FLAMESHOT | Create /.config/flameshot directory
  file:
    path: ~/.config/flameshot
    state: directory

- name: FLAMESHOT | Symlink flameshot config
  file:
    src: "{{ ansible_env.PWD }}/roles/flameshot/files/{{ item }}"
    path: "~/.config/flameshot/{{ item }}"
    state: link
    follow: yes
    force: yes
  loop:
    - flameshot.ini
