- name: Install Flameshot on Linux
  package:
    name:
      - flameshot
    state: latest
  become: yes

- name: Create /.config/flameshot directory
  file:
    path: ~/.config/flameshot
    state: directory

- name: Symlink flameshot config
  file:
    src: "{{ ansible_env.PWD }}/roles/flameshot/files/{{ item }}"
    path: "~/.config/flameshot/{{ item }}"
    state: link
    follow: yes
    force: yes
  loop:
    - flameshot.ini