- name: DUNST | Install Dunst on Linux
  package:
    name:
      - dunst
    state: latest
  become: yes

- name: DUNST | Create /.config/dunst directory
  file:
    path: ~/.config/dunst
    state: directory

- name: DUNST | Symlink dunst config
  file:
    src: "{{ ansible_env.PWD }}/roles/dunst/files/{{ item }}"
    path: "~/.config/dunst/{{ item }}"
    state: link
    follow: yes
    force: yes
  loop:
    - dunstrc
