- name: install Obsidian on linux
  package:
    name: obsidian
    state: latest
  become: yes

- name: symlink obsidian git sync on linux
  file:
    src: "{{ ansible_env.PWD }}/roles/obsidian/files/{{ item }}"
    path: "/usr/bin/{{ item }}"
    state: link
    follow: yes
    force: yes
  loop:
    - _Obsidian.sh
  become: yes
