- name: OBSIDIAN | Install Obsidian on Linux
  package:
    name: obsidian
    state: latest
  become: yes

- name: OBSIDIAN | Symlink _Obsidian script
  file:
    src: "{{ ansible_env.PWD }}/roles/obsidian/files/{{ item }}"
    path: "/usr/bin/{{ item }}"
    state: link
    follow: yes
    force: yes
  loop:
    - _Obsidian.sh
  become: yes
