- name: Install Alacritty on Linux
  package:
    name:
      - rofi
    state: latest
  become: yes

- name: Create /.config/rofi directory
  file:
    path: ~/.config/rofi
    state: directory

- name: Symlink rofi config
  file:
    src: "{{ ansible_env.PWD }}/roles/rofi/files/{{ item }}"
    path: "~/.config/rofi/{{ item }}"
    state: link
    follow: yes
    force: yes
  loop:
    - config.rasi