- name: ROFI | Install rofi on Linux
  package:
    name:
      - rofi
    state: latest
  become: yes

- name: ROFI | Create /.config/rofi directory
  file:
    path: ~/.config/rofi
    state: directory

- name: ROFI | Symlink rofi config
  file:
    src: "{{ ansible_env.PWD }}/roles/rofi/files/{{ item }}"
    path: "~/.config/rofi/{{ item }}"
    state: link
    follow: yes
    force: yes
  loop:
    - config.rasi
