- name: install neovim on linux
  package:
    name:
      - tmux
    state: present
  become: yes

- name: symlink tmux conf on Linux
  file:
    src: "{{ ansible_env.PWD }}/roles/tmux/files/{{ item }}"
    path: "~/{{ item }}"
    state: link
    follow: yes
    force: yes
  loop:
    - .tmux.conf
