- name: Create ~/.ssh directory
  file:
    path: "~/.ssh"
    state: directory

- name: Create ~/.Pictures directory
  file:
    path: "~/Pictures"
    state: directory

- name: Create ~/.Pictures/screenshot directory
  file:
    path: "~/Pictures/screenshot"
    state: directory

- name: Create ~/gitclones directory
  file:
    path: "~/gitclones"
    state: directory

- name: Create ~/junkyard directory
  file:
    path: "~/junkyard"
    state: directory
