- name: Install vim on Macos
  community.general.homebrew:
    name:
      - vim
      - neovim
    state: latest
  when: ansible_facts['os_family'] == "Darwin"

- name: Install vim on Macos
  package:
    name:
      - vim
      - neovim
    state: latest
  become: yes
  when: ansible_facts['os_family'] == "Linux"

- name: Create nvim dir
  file:
    path: "~/.config/nvim/"
    state: directory
    follow: yes
    force: yes

- name: Symlink nvim config
  file:
    src: "{{ ansible_env.PWD }}/roles/vim/files/{{ item }}"
    path: "~/.config/nvim/{{ item }}"
    state: link
    follow: yes
    force: yes
  loop:
    - init.vim