- name: VIM | Install vim on Macos
  community.general.homebrew:
    name:
      - vim
        #      - neovim
    state: latest
  when: ansible_facts['os_family'] == "Darwin"

- name: VIM | Install vim on Macos
  package:
    name:
      - vim
        #     - neovim
    state: latest
  become: yes
  when: ansible_facts['os_family'] == "Linux"

- name: VIM | Create nvim dir
  file:
    path: "~/.config/nvim/"
    state: directory
    follow: yes
    force: yes

- name: VIM | Symlink nvim config
  file:
    src: "{{ ansible_env.PWD }}/roles/vim/files/{{ item }}"
    path: "~/.config/nvim/{{ item }}"
    state: link
    follow: yes
    force: yes
  loop:
    - init.vim


- name: VIM | Symlink vim config
  file:
    src: "{{ ansible_env.PWD }}/roles/vim/files/{{ item }}"
    path: "~/.vimrc"
    state: link
    follow: yes
    force: yes
  loop:
    - init.vim
