- name: install vim on linux
  package:
    name:
      - vim
      - neovim
    state: present
  become: yes

- name: symlink vimrc conf on Linux
  file:
    src: "{{ ansible_env.PWD }}/roles/vimrc/files/{{ item }}"
    path: "~/{{ item }}"
    state: link
    follow: false
    force: yes
  loop:
    - .vimrc
