- name: install AMD CPU driver on ArchLinux
  become: yes
  package:
    name:
      - amd-ucode
      - linux-zen
    state: present
  when: (ansible_facts['os_family'] == "ArchLinux") and (ansible_facts['ansible_processor'].find('AMD') != -1)

- name: install Intel CPU driver on ArchLinux
  become: yes
  package:
    name:
      - intel-ucode
    state: present
  when: (ansible_facts['os_family'] == "ArchLinux") and (ansible_facts['ansible_processor'].find('Intel') != -1)
