- name: GPU | Install AMD driver on Linux
  pacman:
    name:
      - xf86-video-amdgpu
      - lib32-mesa
      - vulkan-radeon
      - lib32-vulkan-radeon
      - vulkan-icd-loader
      - lib32-vulkan-icd-loader
      - linux-zen
    state: latest
    executable: yay
    extra_args: --builddir /var/cache/yay
  when: gpu == 'amd'
