- name: GPU | Install NVIDIA driver on Linux
  pacman:
    name:
      - nvidia
      - nvidia-utils
      - lib32-nvidia-utils
      - nvidia-settings
      - vulkan-icd-loader
      - lib32-vulkan-icd-loader
    state: latest
    executable: yay
    extra_args: --builddir /var/cache/yay